apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "labels_demo.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "labels_demo.name" . }}
data:
  index.html: |
    <pre>
    # High-level knobs
    param1: '{{ .Values.param1 | default "<not set>" }}'
    param2: '{{ .Values.param2 | default "<not set>" }}'
    param3: '{{ .Values.param3 | default "<not set>" }}'
    {{ if eq .Values.param1 "valueA" }}
    param4: 'aaa' # based on value of high-level knob param1
    {{ else }}
    param4: 'xxx' # based on value of high-level knob param1
    {{ end }}
    {{ if eq .Values.param2 "valueB" }}
    param5: 'bbb' # based on value of high-level knob param2
    {{ else }}
    param5: 'yyy' # based on value of high-level knob param2
    {{ end }}
    {{ if eq .Values.param3 "valueC" }}
    param6: 'ccc' # based on value of high-level knob param3
    {{ else }}
    param6: 'zzz' # based on value of high-level knob param3
    {{ end }}
    </pre>
